language: java
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
before_install:
  - chmod +x mvnw
script: "./mvnw clean compile test"
after_success: "./mvnw clean test jacoco:report coveralls:report"