version: '3'
networks:
  eureka-server_myweb:
    external: true
services:
  configserver:
    container_name: "configserver"
    image: spring-cloud-config-server:1.0
    ports:
      - "8888:8888"
    networks:
      - eureka-server_myweb
    environment:
      RUN_MESSAGE: "HELLO !!"